# ==============================================================
# CONFIGURAÇÃO DO SERVIDOR
# ==============================================================
server.port=8080

# ==============================================================
# CONFIGURAÇÃO DO BANCO DE DADOS (POSTGRESQL)
# ==============================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/unoesc_gestao_documentos
spring.datasource.username=postgres
spring.datasource.password=0649
spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================================================
# CONFIGURAÇÃO DO HIBERNATE / JPA
# ==============================================================
# Atualiza o esquema do banco automaticamente baseado nas Entidades Java
spring.jpa.hibernate.ddl-auto=update

# Mostra o SQL gerado no console (excelente para debug e para a avaliação)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true